import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { FruitContextProvider } from './context/fruit'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Know your fruit',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png"></link>
      </head>
      <body className={inter.className}>
        <FruitContextProvider>
          {children}
        </FruitContextProvider>
        </body>
    </html>
  )
}
